/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modelo;

import DAO.ComprasDAO;
import DAO.CompritasDAO;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.util.Date;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Axel Reyez
 */
public class Alta extends javax.swing.JFrame {
    
DefaultTableModel modeloR;
    String cabecera []={"ID","Proveedor","Producto","Precio"};
    String datos[][]={};
    String user;
    int valor=0;
     String BD;
    /**
     * Creates new form Alta
     */
    
    public Alta(String BD,String User) throws ClassNotFoundException, InstantiationException, IllegalAccessException, Exception {
         setTitle("Chapatas bistro");
         this.user=User;
         this.BD=BD;
         
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/logo.jpg")).getImage());
           try {
             UIManager.setLookAndFeel("UpperEssential.UpperEssentialLookAndFeel");
         } catch (UnsupportedLookAndFeelException ex) {
             Logger.getLogger(Chapatas.class.getName()).log(Level.SEVERE, null, ex);
         }
        initComponents();
      Date fecha1 = new Date();
DateFormat df2 = DateFormat.getDateInstance(DateFormat.LONG);
this.fechita.setText(df2.format(fecha1));

    modeloR = new DefaultTableModel(datos,cabecera);
    Registros.setModel(modeloR);
    }
    
   
    void agregarRegistro() throws SQLException
{
    
    
   Object datos1[]={idc.getText(),Proveedorc.getText(),Productoc.getText(),this.Precioc.getText()};
     
    modeloR.addRow(datos1);
  
                
this.Insertar( idc.getText() ,Proveedorc.getText(),Productoc.getText(),Double.parseDouble( Precioc.getText()),this.fechita.getText());

}
public void Insertar(String ID,String nombre,String Producto,Double precio,String Fecha)
{
    ComprasDAO compras = new ComprasDAO(BD);
    compras.RegistrarCompra(ID, nombre, Producto, precio, Fecha);
    CompritasDAO compritas=new CompritasDAO(BD);
    compritas.Agregar(Double.parseDouble( Precioc.getText()));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Registros = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        ID = new javax.swing.JLabel();
        Proveedor = new javax.swing.JLabel();
        Producto = new javax.swing.JLabel();
        Precio = new javax.swing.JLabel();
        idc = new javax.swing.JTextField();
        Proveedorc = new javax.swing.JTextField();
        Productoc = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Precioc = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        fechita = new javax.swing.JLabel();
        altamos = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Registros.setFont(new java.awt.Font("Poor Richard", 0, 14)); // NOI18N
        Registros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Proveedor", "Producto", "Precio", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Registros.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(Registros);

        ID.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        ID.setText("ID");

        Proveedor.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        Proveedor.setText("Proveedor");

        Producto.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        Producto.setText("Producto");

        Precio.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        Precio.setText("Precio ");

        idc.setFont(new java.awt.Font("Poor Richard", 0, 14)); // NOI18N
        idc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                idcMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                idcMouseReleased(evt);
            }
        });
        idc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idcActionPerformed(evt);
            }
        });
        idc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idcKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idcKeyReleased(evt);
            }
        });

        Proveedorc.setFont(new java.awt.Font("Poor Richard", 0, 14)); // NOI18N

        Productoc.setFont(new java.awt.Font("Poor Richard", 0, 14)); // NOI18N
        Productoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductocActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        jButton3.setText("Generar reporte");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        Precioc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0.###"))));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ID)
                            .addComponent(Proveedor)
                            .addComponent(Producto)
                            .addComponent(Precio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Proveedorc)
                            .addComponent(idc)
                            .addComponent(Productoc)
                            .addComponent(Precioc)))
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ID)
                    .addComponent(idc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Proveedor)
                    .addComponent(Proveedorc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Producto)
                    .addComponent(Productoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Precio)
                    .addComponent(Precioc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Poor Richard", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Compras del día");

        jButton4.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        jButton4.setText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        fechita.setFont(new java.awt.Font("Poor Richard", 0, 36)); // NOI18N

        altamos.setText("jButton5");
        altamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altamosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(fechita, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(altamos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(267, 267, 267))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(altamos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fechita, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4))))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProductocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductocActionPerformed
void rellenar()
{
   this.idc.setText(JOptionPane.showInputDialog(null,"ID:"));
   this.Proveedorc.setText(JOptionPane.showInputDialog(null,"Proveedor:"));
   this.Productoc.setText(JOptionPane.showInputDialog(null,"Producto:"));
   this.Precioc.setText(JOptionPane.showInputDialog(null,"Precio:"));
   valor+=Double.parseDouble(this.Precioc.getText());
   DateFormat df= DateFormat.getDateInstance();
Date fecha1 = new Date();
DateFormat df2 = DateFormat.getDateInstance(DateFormat.SHORT);

}
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      this.Precioc.setEnabled(false);
      this.Productoc.setEnabled(false);
      this.Proveedorc.setEnabled(false);
      this.altamos.setVisible(false);
     //this.jButton5.doClick();

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
limpiar();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
void limpiar()
{
    idc.setText("");
    this.Proveedorc.setText("");
    this.Productoc.setText("");
    this.Precioc.setText("");
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        
        if("".equals(idc.getText()) && "".equals(Proveedorc.getText()) && "".equals(Productoc.getText()) && "".equals(Precioc.getText()) )
        {
            int opcion = JOptionPane.showOptionDialog(null, "Agregar registro", "ADVERTENCIA!", 2, JOptionPane.WARNING_MESSAGE, null, new String[]{"Asistido", "Manual"}, null); 
                     if (opcion==0)
                     {
                         rellenar();
                         this.jButton1.doClick();
                         
                     }
        }
        else if(!"".equals(idc.getText()) && !"".equals(Proveedorc.getText()) && !"".equals(Productoc.getText()) && !"".equals(Precioc.getText()) )
        {
        int resp = JOptionPane.showConfirmDialog(null,"Esta seguro que desea agregar este registro?");
        if(JOptionPane.OK_OPTION == resp)
        {
            try {
                agregarRegistro();
                
            } catch (SQLException ex) {
                Logger.getLogger(Alta.class.getName()).log(Level.SEVERE, null, ex);
            }
        limpiar();
        }
        }
        else if(!"".equals(idc.getText()) || !"".equals(Proveedorc.getText()) || !"".equals(Productoc.getText())||  !"".equals(Precioc.getText()))
        {
            JOptionPane.showMessageDialog(null,"Verifique todos los campos");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed
void actualizarGastos(double ticket)
{
ComprasDAO com=new ComprasDAO(BD);
com.Agregar(ticket);
}
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        
    
    
   Object datos1[]={ID.getText(),Proveedor.getText(),Producto.getText(),this.Precio.getText(),this.fechita.getText()};
    String hoy,nombrearchivo,turno1,cadena="C:\\Users\\"+user+"\\Documents\\Reportes\\",inicio,fin;

    
nombrearchivo="Reporte"+fechita.getText();



 
 Document documento = new Document();
 FileOutputStream ficheroPdf;
 String fin2 = null;
 try 
{
    
    fin2=cadena+nombrearchivo+".pdf";
    System.out.println(fin2);
 ficheroPdf = new FileOutputStream(fin2);
 PdfWriter.getInstance(
                       documento, 
                       ficheroPdf
                       ).setInitialLeading(20);
}
catch (FileNotFoundException | DocumentException ex) 
{
 System.out.println(ex.toString());
}


try{
 documento.open();
 
        Paragraph para1=new Paragraph();
        documento.add(new Paragraph("Chatapas Bistro ",FontFactory.getFont("arial",30)));
        Paragraph parrafo2 = new Paragraph("Fecha: " + fechita.getText() ,FontFactory.getFont("arial",25));
    parrafo2.setAlignment(2);
        
        documento.add(parrafo2);
PdfPTable tabla = new PdfPTable(4);
float[] medidaCeldas = {2f,7f,4f,3f};
tabla.setWidths(medidaCeldas);
documento.add(new Paragraph("\n"));
    //el numero indica la cantidad de Columnas
int num=25;
    tabla.addCell(new Paragraph(("ID"),FontFactory.getFont("arial",num)));
    tabla.addCell(new Paragraph(("Proveedor"),FontFactory.getFont("arial",num)));
    tabla.addCell(new Paragraph(("Producto"),FontFactory.getFont("arial",num)));
    tabla.addCell(new Paragraph(("Precio"),FontFactory.getFont("arial",num)));
    documento.add(new Paragraph("\n"));
    PdfPCell celda,celda1; 
        
    for(int i=0; i< modeloR.getRowCount();i++)
        {
            int num1=20;
            celda = new PdfPCell (new Paragraph((String) modeloR.getValueAt(i,0),  FontFactory.getFont("arial",num1)));
            String n,x;
            
           n=modeloR.getValueAt(i,1).toString();
            celda1 = new PdfPCell (new Paragraph(n,FontFactory.getFont("arial",num1)));
     PdfPCell celda2 = new PdfPCell (new Paragraph((String) modeloR.getValueAt(i,2),  FontFactory.getFont("arial",num1)));
     PdfPCell celda3 = new PdfPCell (new Paragraph((String) modeloR.getValueAt(i,3),  FontFactory.getFont("arial",num1)));
            
           celda1.setBorder(0);
            tabla.addCell(celda);
           tabla.addCell(celda1);
           tabla.addCell(celda2);
           tabla.addCell(celda3);
          
           tabla.completeRow();
            modeloR.removeRow(i);
            i=i-1;
        }
    documento.add(tabla);
    documento.add(new Paragraph("\n"));
   documento.add(new Paragraph("Gastos totales:"+valor,  FontFactory.getFont("arial",25)));
 

     
 documento.close();
}catch(Exception ex){
 System.out.println(ex.toString());
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void idcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idcKeyReleased

        // TODO add your handling code here:
    }//GEN-LAST:event_idcKeyReleased

    private void idcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idcActionPerformed
  
       // TODO add your handling code here:
    }//GEN-LAST:event_idcActionPerformed

    private void idcKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idcKeyPressed
  String id="Prueba";
         char car=(char) evt.getKeyCode();
if(car==evt.VK_ENTER)
{
    id=idc.getText();
    buscardatos(id);
         Date fecha1 = new Date();
DateFormat df2 = DateFormat.getDateInstance(DateFormat.LONG);
this.fechita.setText(df2.format(fecha1));
}
        else
        {
            System.out.print("holi");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_idcKeyPressed

    private void idcMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idcMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_idcMouseReleased

    private void idcMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idcMouseExited
         // TODO add your handling code here:
    }//GEN-LAST:event_idcMouseExited

    private void altamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altamosActionPerformed
this.ActualizarTabla();        // TODO add your handling code here:
    }//GEN-LAST:event_altamosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
String id=(String)Registros.getValueAt(Registros.getSelectedRow(),0);
String nombre=(String)Registros.getValueAt(Registros.getSelectedRow(),1);
Double precio=(Double)Registros.getValueAt(Registros.getSelectedRow(),3);
String producto=(String)Registros.getValueAt(Registros.getSelectedRow(),2);
this.EliminarRegistro(id, producto, precio, this.fechita.getText(), nombre);
this.modeloR.removeRow(this.Registros.getSelectedRow());

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed
public void EliminarRegistro(String id ,String proveedor,Double precio,String fecha,String nombre)
{
    ComprasDAO compritas=new ComprasDAO(BD);
    compritas.EliminarCompra(id,proveedor,precio,fecha,nombre);
    CompritasDAO compras=new CompritasDAO(BD);
    compras.Eliminar(precio);
    
}
    void buscardatos(String id)
{
    ComprasDAO c=new ComprasDAO(BD);
    compra co=c.BuscarId(id);
    this.Proveedorc.setEnabled(true);
    this.Productoc.setEnabled(true);
    this.Precioc.setEnabled(true);
    if(co!=null)
    this.Proveedorc.setText(co.getNombre());
}

public void ActualizarTabla()
{
    ComprasDAO c=new ComprasDAO(BD);
    LinkedList ls=c.BuscarFecha(this.fechita.getText());
    while(!ls.isEmpty())
    {
        compra co=new compra((compra)ls.pop());
        Object datos1[]={co.getId(),co.getNombre(),co.getProducto(),co.getPrecio()};
        modeloR.addRow(datos1);
    }         
}
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID;
    private javax.swing.JLabel Precio;
    private javax.swing.JFormattedTextField Precioc;
    private javax.swing.JLabel Producto;
    private javax.swing.JTextField Productoc;
    private javax.swing.JLabel Proveedor;
    private javax.swing.JTextField Proveedorc;
    private javax.swing.JTable Registros;
    public javax.swing.JButton altamos;
    private javax.swing.JLabel fechita;
    private javax.swing.JTextField idc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
