/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modelo;

/**
 *
 * @author Axel Reyez
 */
public class info extends javax.swing.JPanel {

    /**
     * Creates new form info
     */
    public info() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Total7 = new javax.swing.JLabel();
        Nombrellevar = new javax.swing.JTextField();
        Pago7 = new javax.swing.JLabel();
        Telefonollevar = new javax.swing.JTextField();
        Cambio7 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        Direccionllevar = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));

        Total7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Total7.setForeground(new java.awt.Color(51, 51, 255));
        Total7.setText("Nombre:");

        Nombrellevar.setForeground(new java.awt.Color(0, 51, 204));
        Nombrellevar.setText("-");

        Pago7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Pago7.setForeground(new java.awt.Color(51, 51, 255));
        Pago7.setText("Telefono:");

        Telefonollevar.setForeground(new java.awt.Color(0, 51, 204));
        Telefonollevar.setText("-");
        Telefonollevar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonollevarActionPerformed(evt);
            }
        });

        Cambio7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Cambio7.setForeground(new java.awt.Color(51, 51, 255));
        Cambio7.setText("Dirección:");

        Direccionllevar.setColumns(20);
        Direccionllevar.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        Direccionllevar.setRows(5);
        jScrollPane9.setViewportView(Direccionllevar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Pago7)
                    .addComponent(Cambio7)
                    .addComponent(Total7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nombrellevar, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Telefonollevar, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Total7)
                    .addComponent(Nombrellevar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pago7)
                    .addComponent(Telefonollevar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cambio7)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TelefonollevarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonollevarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonollevarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cambio7;
    private javax.swing.JTextArea Direccionllevar;
    private javax.swing.JTextField Nombrellevar;
    private javax.swing.JLabel Pago7;
    private javax.swing.JTextField Telefonollevar;
    private javax.swing.JLabel Total7;
    private javax.swing.JScrollPane jScrollPane9;
    // End of variables declaration//GEN-END:variables
}
