/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modelo;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

import javax.swing.JOptionPane;


/**
 *
 * @author Axel Reyez
 */
public class Reporte extends javax.swing.JFrame {
    String BD;
    Conection db=new Conection();
    public Reporte(String BD) throws Exception {
         this.BD=BD;
        db.MySQLConnection(BD,"root","root");
        setTitle("Chapatas bistro");
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/logo.jpg")).getImage());
        
        initComponents();
        reloj hilo=new reloj(Hora);
        this.generar.setVisible(false);
this.limpiar.setVisible(true);
this.jLabel1.setVisible(false);
this.jTextField1.setVisible(false);
hilo.start();
DateFormat df= DateFormat.getDateInstance();
Date Fecha = new Date();
DateFormat df2 = DateFormat.getDateInstance(DateFormat.LONG);
Dia.setText(df2.format(Fecha));
    }

    ResultSet rs;
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        generar = new javax.swing.JButton();
        regresar = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        Dia = new javax.swing.JLabel();
        Hora = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem1");
        jPopupMenu1.add(jMenuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel1.setText("ID:");

        jTextField1.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jTextField1.setText("-");
        jTextField1.setComponentPopupMenu(jPopupMenu1);

        generar.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        generar.setText("Generar");
        generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarActionPerformed(evt);
            }
        });

        regresar.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });

        limpiar.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });

        Dia.setFont(new java.awt.Font("Poor Richard", 0, 30)); // NOI18N
        Dia.setForeground(new java.awt.Color(255, 255, 255));
        Dia.setText("jLabel3");

        Hora.setFont(new java.awt.Font("Poor Richard", 0, 30)); // NOI18N
        Hora.setForeground(new java.awt.Color(255, 255, 255));
        Hora.setText("jLabel4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(generar)
                        .addGap(18, 18, 18)
                        .addComponent(limpiar)
                        .addGap(13, 13, 13)
                        .addComponent(regresar)))
                .addGap(324, 324, 324))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Dia, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Hora)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Dia, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Hora)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generar)
                    .addComponent(regresar)
                    .addComponent(limpiar))
                .addGap(31, 31, 31))
        );

        jMenu1.setText("Reportes");
        jMenu1.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N

        jMenuItem1.setText("Por Id");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
this.generar.setVisible(true);
this.regresar.setVisible(true);
this.limpiar.setVisible(true);
this.jLabel1.setVisible(true);
this.jTextField1.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarActionPerformed
if(this.jTextField1.getText().equals("") || this.jTextField1.getText().equals("-") )  
{
    JOptionPane.showMessageDialog(null,"Verifique el campo");
}
else
{
    importar(this.jTextField1.getText());
}
        // TODO add your handling code here:
    }//GEN-LAST:event_generarActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed

        this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_regresarActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
this.jTextField1.setText("-");        // TODO add your handling code here:
    }//GEN-LAST:event_limpiarActionPerformed

    /**
     * @param args the command line arguments
     */
   void importar(String valor)
   {
        String hoy,nombrearchivo,turno1,cadena="C:\\Users\\Chatapas\\Documents\\Reportes\\";

        hoy=Dia.getText();

        nombrearchivo="Reporte-"+valor+"-"+hoy+ ".pdf";

        Document documento = new Document();
        FileOutputStream ficheroPdf;
        String fin ;
        try
        {

            fin=cadena+nombrearchivo;
            ficheroPdf = new FileOutputStream(fin);
            PdfWriter.getInstance(
                documento,
                ficheroPdf
            ).setInitialLeading(20);
        }
        catch (FileNotFoundException ex)
        {
            System.out.println(ex.toString());
        } catch (DocumentException ex) {
            Logger.getLogger(Chapatas.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {

            rs=db.getStatement().executeQuery("SELECT  * FROM compras where ID='"+valor+"'");
            documento.open();
            Paragraph para1=new Paragraph();
            documento.add(new Paragraph("Chatapas Bistro ",FontFactory.getFont("arial",30)));
            Paragraph parrafo2 = new Paragraph("Reporte de compras  Generado el: " + Dia.getText()+ " \n Hora de registro : " + Hora.getText()+"\n\n",FontFactory.getFont("arial",30));
            parrafo2.setAlignment(0);
            documento.add(parrafo2);
            Paragraph parrafo3 = new Paragraph("ID: " + valor +"\n\n ",FontFactory.getFont("arial",30));
            parrafo3.setAlignment(0);
            documento.add(parrafo3);
            PdfPTable tabla = new PdfPTable(3);
tabla.setWidthPercentage(100);
float[] medidaCeldas = {5f,8f,6f};
tabla.setWidths(medidaCeldas);
PdfPCell celda,celda1,celda2,celda3,celda4,celda5; 
int total=0;
           celda = new PdfPCell (new Paragraph("Producto",  FontFactory.getFont("arial",20)));

            celda1 = new PdfPCell (new Paragraph("Precio",FontFactory.getFont("arial",20)));
           
           celda2 = new PdfPCell (new Paragraph("Fecha",FontFactory.getFont("arial",20)));
           tabla.addCell(celda);
           tabla.addCell(celda1);
           tabla.addCell(celda2);

           tabla.completeRow();
            while(rs.next())
            {
                String nombre="",fecha="";
                int precio=0;
                nombre=rs.getString("Producto");
                fecha=rs.getString("Fecha");
                precio=rs.getInt("Costo");
                total+=precio;
           celda = new PdfPCell (new Paragraph(nombre,  FontFactory.getFont("arial",20)));

            celda1 = new PdfPCell (new Paragraph(Integer.toString(precio),FontFactory.getFont("arial",20)));
           
           celda2 = new PdfPCell (new Paragraph(fecha,FontFactory.getFont("arial",20)));
          
            tabla.addCell(celda);
           tabla.addCell(celda1);
           tabla.addCell(celda2);

           tabla.completeRow();
               
            }
            documento.add(tabla);
            Paragraph parrafo6 = new Paragraph("\nTotal invertido: "+"$"+total ,FontFactory.getFont("arial",30));
            parrafo6.setAlignment(2);
            documento.add(parrafo6); 
            

         

            documento.close();
            JOptionPane.showMessageDialog(null,"Reporte generado con exito");
        }catch (SQLException sqle)
        {
            System.out.println(sqle.getMessage());
            System.exit(0);
        } catch (DocumentException ex) {
            Logger.getLogger(Reporte.class.getName()).log(Level.SEVERE, null, ex);
        }
      
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Dia;
    private javax.swing.JLabel Hora;
    private javax.swing.JButton generar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton limpiar;
    private javax.swing.JButton regresar;
    // End of variables declaration//GEN-END:variables
}
